#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RoadWeatherMobileApp.Droid.Resource", IsApplication=true)]

namespace RoadWeatherMobileApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CITOAndroidCommon.Resource.String.ApplicationName = global::RoadWeatherMobileApp.Droid.Resource.String.ApplicationName;
			global::CITOAndroidCommon.Resource.String.Hello = global::RoadWeatherMobileApp.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fog = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icy = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icy2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icy3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int slippery = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int slippery2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int slippery3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int snowy = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int snowy2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int snowy3 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int speed_harm_10 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int speed_harm_15 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int speed_harm_20 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int speed_harm_25 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int speed_harm_30 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int speed_harm_35 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int speed_harm_40 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int speed_harm_45 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int speed_harm_50 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int speed_harm_55 = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
