//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    
    public enum ActionCode : int
    {
        None = 0,
        UseCaution = 1,
        DriveSlowlyAndUseCaution = 2,
        DelayTravelSeekAlternateRouteOrDriveSlowlyAndUseExtremeCaution = 3
    }
}
