//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_TSSDetectionZone
    {
        public string DSId { get; set; }
        public string DZId { get; set; }
        public string DZType { get; set; }
        public int LaneNumber { get; set; }
        public string LaneType { get; set; }
        public string LaneDescription { get; set; }
        public string DataType { get; set; }
        public string DZStatus { get; set; }
        public string Direction { get; set; }
        public string RoadwayId { get; set; }
    }
}
