//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public int Id { get; set; }
        public int EDMSSAlertId { get; set; }
        public string Name { get; set; }
        public string Hr06AlertSummaryCode { get; set; }
        public string Hr24AlertSummaryCode { get; set; }
        public string Hr72AlertSummaryCode { get; set; }
        public double MaxLatitude { get; set; }
        public double MaxLongitude { get; set; }
        public double MinLatitude { get; set; }
        public double MinLongitude { get; set; }
        public string ObservAlertSummaryCode { get; set; }
    
        public virtual EDMSSAlert EDMSSAlert { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}
