//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDMSSAlert
    {
        public EDMSSAlert()
        {
            this.Districts = new HashSet<District>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<District> Districts { get; set; }
    }
}
