//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Configuration_ESS> Configuration_ESS { get; set; }
        public virtual DbSet<Configuration_INFLOThresholds> Configuration_INFLOThresholds { get; set; }
        public virtual DbSet<Configuration_Roadway> Configuration_Roadway { get; set; }
        public virtual DbSet<Configuration_RoadwayESS> Configuration_RoadwayESS { get; set; }
        public virtual DbSet<Configuration_RoadwayLinks> Configuration_RoadwayLinks { get; set; }
        public virtual DbSet<Configuration_RoadwayLinksDetectorStation> Configuration_RoadwayLinksDetectorStation { get; set; }
        public virtual DbSet<Configuration_RoadwayLinksESS> Configuration_RoadwayLinksESS { get; set; }
        public virtual DbSet<Configuration_RoadwayMileMarkers> Configuration_RoadwayMileMarkers { get; set; }
        public virtual DbSet<Configuration_RoadwaySubLinks> Configuration_RoadwaySubLinks { get; set; }
        public virtual DbSet<Configuration_TSSDetectionZone> Configuration_TSSDetectionZone { get; set; }
        public virtual DbSet<Configuration_TSSDetectorStation> Configuration_TSSDetectorStation { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TME_CVData_Input> TME_CVData_Input { get; set; }
        public virtual DbSet<TME_CVData_Input_Processed> TME_CVData_Input_Processed { get; set; }
        public virtual DbSet<TME_CVData_SubLink> TME_CVData_SubLink { get; set; }
        public virtual DbSet<TME_ESSData_Input> TME_ESSData_Input { get; set; }
        public virtual DbSet<TME_ESSMobileData_Input> TME_ESSMobileData_Input { get; set; }
        public virtual DbSet<TME_TSSData_Input> TME_TSSData_Input { get; set; }
        public virtual DbSet<TME_TSSESS_Link> TME_TSSESS_Link { get; set; }
        public virtual DbSet<TMEOutput_QWARN_QueueInfo> TMEOutput_QWARN_QueueInfo { get; set; }
        public virtual DbSet<TMEOutput_QWARNMessage_CV> TMEOutput_QWARNMessage_CV { get; set; }
        public virtual DbSet<TMEOutput_ShockWaveInformation> TMEOutput_ShockWaveInformation { get; set; }
        public virtual DbSet<TMEOutput_SPDHARMMessage_CV> TMEOutput_SPDHARMMessage_CV { get; set; }
        public virtual DbSet<TMEOutput_SPDHARMMessage_Infrastructure> TMEOutput_SPDHARMMessage_Infrastructure { get; set; }
        public virtual DbSet<TMEOutput_WRTM_Alerts> TMEOutput_WRTM_Alerts { get; set; }
        public virtual DbSet<RoadWeatherProbeInputs> RoadWeatherProbeInputs { get; set; }
        public virtual DbSet<MAWOutput> MAWOutputs { get; set; }
        public virtual DbSet<WeatherEvent> WeatherEvents { get; set; }
        public virtual DbSet<EDMSSAlert> EDMSSAlerts { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SiteObservation> SiteObservations { get; set; }
    }
}
