//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    
    public enum PavementCode : int
    {
        Clear = 0,
        WetRoads = 1,
        SnowyRoads = 2,
        SnowySlickRoads = 3,
        IcyRoads = 4,
        IcySlickRoads = 5,
        HydroplaningPossible = 6,
        BlackIce = 7,
        IcyRoadsPossible = 8,
        IcySlickRoadsPossible = 9
    }
}
