//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    
    public enum PrecipitationCode : int
    {
        Clear = 0,
        LightRain = 1,
        ModerateRain = 2,
        HeavyRain = 3,
        LightRainSnowMix = 4,
        ModerateRainSnowMix = 5,
        HeavyRainSnowMix = 6,
        LightSnow = 7,
        ModerateSnow = 8,
        HeavySnow = 9
    }
}
