//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.SiteObservations = new HashSet<SiteObservation>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Hr06AlertSummaryCode { get; set; }
        public string Hr24AlertSummaryCode { get; set; }
        public string Hr72AlertSummaryCode { get; set; }
        public bool IsRoadCondSite { get; set; }
        public bool IsWeatherObservSite { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string ObservAlertCode { get; set; }
        public string SiteIdName { get; set; }
        public long SiteNum { get; set; }
        public int DistrictId { get; set; }
        public Nullable<double> MileMarker { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<SiteObservation> SiteObservations { get; set; }
    }
}
