//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    
    public enum VisibilityCode : int
    {
        Clear = 0,
        LowVisibility = 1,
        BlowingSnow = 2,
        Fog = 3,
        Haze = 4,
        Dust = 5,
        Smoke = 6
    }
}
