//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherLog
    {
        public int Id { get; set; }
        public short PaveCntClear { get; set; }
        public short PaveCntWet { get; set; }
        public short PaveCntSnow { get; set; }
        public short PaveCntIce { get; set; }
        public short PrecipCntClear { get; set; }
        public short PrecipCntWet { get; set; }
        public short PrecipCntSnow { get; set; }
        public short PrecipCntIce { get; set; }
        public short TotalReportedSites { get; set; }
        public System.DateTime Time { get; set; }
        public double RoadTempAvg { get; set; }
        public string Message { get; set; }
        public Nullable<int> WeatherEventId { get; set; }
    }
}
